apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server
  labels:
    app: oauth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-server
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      containers:
        - name: oauth-server
          image: your-registry-url/your-repo/oauth-server:v1.0.0
          ports:
            - containerPort: 8080
