definitions:
  login.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  login.IntrospectionResponse:
    properties:
      active:
        type: boolean
      exp:
        type: integer
      scope:
        type: string
    type: object
  login.KeysResponse:
    properties:
      keys:
        items:
          $ref: '#/definitions/login.SignKey'
        type: array
    type: object
  login.SignKey:
    properties:
      algorithm:
        type: string
      key_id:
        type: string
      public_key:
        type: string
      use:
        type: string
    type: object
  login.TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is API server.
  termsOfService: http://swagger.io/terms/
  title: OAuth 2 Server
  version: "1.0"
paths:
  /v1/oauth2/introspect:
    get:
      description: This endpoint allows introspection of the issued JWT Access Tokens.
      operationId: introspect-jwt
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.IntrospectionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/login.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Introspection endpoint (rfc7662) to introspect the issued JWT Access
        Tokens
      tags:
      - token
    post:
      description: This endpoint allows introspection of the issued JWT Access Tokens.
      operationId: introspect-jwt
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.IntrospectionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/login.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Introspection endpoint (rfc7662) to introspect the issued JWT Access
        Tokens
      tags:
      - token
  /v1/oauth2/keys:
    get:
      description: This endpoint lists the signing keys.
      operationId: list-keys
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.KeysResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/login.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Endpoint to list the signing keys (rfc7517)
      tags:
      - token
  /v1/oauth2/onboard:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This endpoint helps local tests, by creating signing keys and declaring
        new clients
      operationId: declare-clients-and-keys
      parameters:
      - description: totp code
        in: formData
        name: totp
        required: true
        type: string
      - default: create_key
        description: operation_type can be create_key (should provide key_name) and
          create_client (should provide client_id, client_secret and associated key_name).
        in: formData
        name: operation_type
        required: true
        type: string
      - default: test
        description: client_id
        in: formData
        name: client_id
        type: string
      - default: test
        description: client_secret
        in: formData
        name: client_secret
        type: string
      - default: my_key
        description: key_name
        in: formData
        name: key_name
        required: true
        type: string
      responses:
        "202":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/login.ErrorResponse'
      summary: Facilitates the creation of signing keys and onboarding new clients
        (client_id, client_secret and signing key pairs)
      tags:
      - token
  /v1/oauth2/token:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This endpoint issues JWT Access Tokens using the Client Credentials
        Grant with Basic Authentication.
      operationId: create-token
      parameters:
      - default: client_credentials
        description: grant_type
        in: formData
        name: grant_type
        required: true
        type: string
      - default: test
        description: client_id
        in: formData
        name: client_id
        required: true
        type: string
      - default: test
        description: client_secret
        in: formData
        name: client_secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/login.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/login.ErrorResponse'
      summary: Issues JWT Access Tokens (rfc7519) using Client Credentials Grant with
        Basic Authentication (rfc6749)
      tags:
      - token
securityDefinitions:
  BasicAuth:
    type: basic
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
